#include "unity.h"
#include "mock_sensor_reader.h"      // Generated by CMock from sensor_reader.h
#include "processing/data_processor.h" // The module under test
#include <string.h> // For strcmp in assertions if needed, or general string ops
#include <stdint.h> // For intptr_t if comparing pointers with NULL via TEST_ASSERT_EQUAL_INT

// setUp and tearDown are called by Unity before/after each test
void setUp(void) {
    mock_sensor_reader_Init(); // Initialize the mock framework before each test
}

void tearDown(void) {
    mock_sensor_reader_Verify();   // Verify all expectations were met
    mock_sensor_reader_Destroy(); // Clean up mock framework after each test
}

void test_initialize_sensor_system_success(void) {
    uint8_t self_test_code_val_to_return = 0x00; // Value mock will write via ReturnThruPtr

    sensor_init_ExpectAndReturn(true);
    // For sensor_self_test, we expect it to be called, it should return true,
    // and it should write 0x00 to the pointer it receives.
    sensor_self_test_ExpectAnyArgsAndReturn(true); // Or Expect specific pointer if we want to check that too
    sensor_self_test_ReturnThruPtr_result_code(&self_test_code_val_to_return);

    sensor_system_status_t status = initialize_sensor_system();
    TEST_ASSERT_EQUAL_INT(SENSOR_STATUS_OK, status);
}

void test_initialize_sensor_system_init_fails(void) {
    sensor_init_ExpectAndReturn(false);
    // sensor_self_test should not be called if init fails, so no Expect for it.

    sensor_system_status_t status = initialize_sensor_system();
    TEST_ASSERT_EQUAL_INT(SENSOR_STATUS_ERROR_INIT, status);
}

void test_initialize_sensor_system_self_test_returns_false(void) {
    sensor_init_ExpectAndReturn(true);
    sensor_self_test_ExpectAnyArgsAndReturn(false); // Self test function itself returns false

    sensor_system_status_t status = initialize_sensor_system();
    TEST_ASSERT_EQUAL_INT(SENSOR_STATUS_ERROR_SELF_TEST, status);
}

void test_initialize_sensor_system_self_test_bad_result_code(void) {
    uint8_t self_test_code_val_to_return = 0x01; // Sensor self-test indicates an error code

    sensor_init_ExpectAndReturn(true);
    sensor_self_test_ExpectAnyArgsAndReturn(true); // Function call itself is successful
    sensor_self_test_ReturnThruPtr_result_code(&self_test_code_val_to_return); // But it writes an error code

    sensor_system_status_t status = initialize_sensor_system();
    TEST_ASSERT_EQUAL_INT(SENSOR_STATUS_ERROR_SELF_TEST, status);
}

void test_process_and_format_sensor_data_success(void) {
    char buffer[50];
    int16_t mock_temp = 255; // Represents 25.5C
    uint16_t mock_hum = 602; // Represents 60.2%RH

    sensor_read_temperature_degrees_c_ExpectAndReturn(mock_temp);
    sensor_read_humidity_percent_rh_ExpectAndReturn(mock_hum);

    bool result = process_and_format_sensor_data(buffer, sizeof(buffer));
    TEST_ASSERT_TRUE(result);
    TEST_ASSERT_EQUAL_STRING("T:25.5C, H:60.2%", buffer);
}

void test_process_and_format_sensor_data_buffer_too_small(void) {
    char buffer[10]; // Intentionally too small for "T:25.5C, H:60.2%"
    int16_t mock_temp = 255;
    uint16_t mock_hum = 602;

    sensor_read_temperature_degrees_c_ExpectAndReturn(mock_temp);
    sensor_read_humidity_percent_rh_ExpectAndReturn(mock_hum);
    // snprintf will write what it can and report how many chars it *would* have written.
    // The process_and_format_sensor_data function checks this.

    bool result = process_and_format_sensor_data(buffer, sizeof(buffer));
    TEST_ASSERT_FALSE(result);
    // Optionally, check the truncated content if behavior is defined.
    // e.g., if it's guaranteed to write "T:25.5C," (9 chars)
    // TEST_ASSERT_EQUAL_STRING_LEN("T:25.5C,", buffer, 9);
}

void test_process_and_format_sensor_data_null_buffer(void) {
    // No expectations for sensor reads needed as it should fail (return false) early due to NULL buffer.
    bool result = process_and_format_sensor_data(NULL, 50);
    TEST_ASSERT_FALSE(result);
}

void test_process_and_format_sensor_data_zero_buffer_size(void) {
    char buffer[1]; // A non-NULL buffer, but effective size for snprintf is 0.
    bool result = process_and_format_sensor_data(buffer, 0);
    TEST_ASSERT_FALSE(result);
}
